# Generated by Django 4.2.10 on 2024-05-03 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songcatalog", "0002_remove_songinstance_due_back_songinstance_mysongs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="songinstance",
            name="imprint",
        ),
    ]
